/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export interface CreateApartmentDto {
  address: string;
  email: string;
  iban?: string;
  image?: string;
  name: string;
  owner?: string;
  pid?: string;
}
