/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export interface CreateGuestDto {
  address: string;
  city: string;
  country: string;
  dateOfArrival: string;
  dateOfBirth: string;
  dateOfDeparture: string;
  name: string;
  note?: string;
  numberOfInvoice?: number;
  PID?: string;
  travelIdNumber: string;
}
