/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { NewGuestInfo } from './newGuestInfo';
import type { OldGuestInfo } from './oldGuestInfo';

export interface CreateGuestDto {
  newGuestInfo: NewGuestInfo;
  oldGuestInfo: OldGuestInfo;
}
