/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { CreateApartmentDtoImage } from './createApartmentDtoImage';

export interface CreateApartmentDto {
  address: string;
  email: string;
  iban?: string;
  image?: CreateApartmentDtoImage;
  name: string;
  owner?: string;
  pid?: string;
  pricePerNight?: number;
}
