/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { EventsData } from './eventsData';

export interface Events {
  apartmentId: string;
  /** @nullable */
  data: EventsData;
  userId: string;
}
