/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { EventObject } from './eventObject';

/**
 * @nullable
 */
export type EventsData = {
  [key: string]: { [key: string]: EventObject[] | null } | null;
} | null;
