/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { EventObject } from './eventObject';

export type EventsData = {
  [key: string]: { [key: string]: EventObject[] | null } | null;
} | null;
