/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export interface EventObject {
  booking?: boolean;
  color?: string;
  description?: string;
  end: string;
  guestId: string;
  id: string;
  phone: string;
  price?: string;
  start: string;
  title: string;
  weekNumber?: number;
}
