/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { GuestObject } from './guestObject';

/**
 * @nullable
 */
export type GuestsData = {
  [key: string]: { [key: string]: GuestObject[] | null } | null;
} | null;
