/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export * from './apiErrorResponse';
export * from './createApartmentDto';
export * from './createApartmentDtoImage';
export * from './createEventDto';
export * from './createGuestDto';
export * from './createUserDto';
export * from './eventObject';
export * from './events';
export * from './eventsData';
export * from './loginResponse';
export * from './newGuestInfo';
export * from './oldGuestInfo';
export * from './removeEventDto';
export * from './removeGuestDto';
export * from './singleApartmentDto';
export * from './updateApartmentDto';
export * from './updateApartmentDtoImage';
export * from './updateEventDto';
export * from './user';
