/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { PublicEvents } from './publicEvents';

export interface PublicEventsResponse {
  apartmentEmail: string;
  apartmentLogo: string;
  apartmentName: string;
  events: PublicEvents;
}
