/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { PublicEventObject } from './publicEventObject';

/**
 * @nullable
 */
export type PublicEventsData = {
  [key: string]: { [key: string]: PublicEventObject[] | null } | null;
} | null;
