/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export interface RemoveGuestDto {
  endDate: string;
  guestId: string;
  startDate: string;
}
