/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export interface RemoveEventDto {
  booking?: boolean;
  color?: string;
  description?: string;
  end: string;
  id?: string;
  name: string;
  phone: string;
  price?: string;
  start: string;
  weekNumber?: number;
}
