/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export interface SingleApartmentDto {
  address: string;
  email: string;
  iban: string;
  id: string;
  image?: string;
  name: string;
  owner: string;
  pid: string;
  pricePerNight?: number;
}
