/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { OldEvent } from './oldEvent';
import type { UpdateEvent } from './updateEvent';

export interface UpdateEventDto {
  oldEvent: OldEvent;
  updatedEvent: UpdateEvent;
}
