/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateApartmentDtoImage } from './updateApartmentDtoImage';

export interface UpdateApartmentDto {
  address: string;
  email: string;
  iban?: string;
  image?: UpdateApartmentDtoImage;
  name: string;
  owner?: string;
  pid?: string;
}
