/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */

export interface User {
  _id: string;
  email: string;
  role: string;
}
