/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  CreateEventDto,
  RemoveEventDto,
  UpdateEventDto,
} from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const eventsControllerAddNew = (
  id: string | undefined | null,
  createEventDto: BodyType<CreateEventDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<CreateEventDto>(
    {
      url: `/events/${id}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createEventDto,
    },
    options
  );
};

export const getEventsControllerAddNewMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerAddNew>>,
    TError,
    { id: string; data: BodyType<CreateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof eventsControllerAddNew>>,
  TError,
  { id: string; data: BodyType<CreateEventDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof eventsControllerAddNew>>,
    { id: string; data: BodyType<CreateEventDto> }
  > = props => {
    const { id, data } = props ?? {};

    return eventsControllerAddNew(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EventsControllerAddNewMutationResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerAddNew>>
>;
export type EventsControllerAddNewMutationBody = BodyType<CreateEventDto>;
export type EventsControllerAddNewMutationError = ErrorType<unknown>;

export const useEventsControllerAddNew = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerAddNew>>,
    TError,
    { id: string; data: BodyType<CreateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getEventsControllerAddNewMutationOptions(options);

  return useMutation(mutationOptions);
};
export const eventsControllerUpdateExisting = (
  id: string | undefined | null,
  updateEventDto: BodyType<UpdateEventDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/events/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateEventDto,
    },
    options
  );
};

export const getEventsControllerUpdateExistingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
    TError,
    { id: string; data: BodyType<UpdateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
  TError,
  { id: string; data: BodyType<UpdateEventDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
    { id: string; data: BodyType<UpdateEventDto> }
  > = props => {
    const { id, data } = props ?? {};

    return eventsControllerUpdateExisting(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EventsControllerUpdateExistingMutationResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerUpdateExisting>>
>;
export type EventsControllerUpdateExistingMutationBody =
  BodyType<UpdateEventDto>;
export type EventsControllerUpdateExistingMutationError = ErrorType<unknown>;

export const useEventsControllerUpdateExisting = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
    TError,
    { id: string; data: BodyType<UpdateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions =
    getEventsControllerUpdateExistingMutationOptions(options);

  return useMutation(mutationOptions);
};
export const eventsControllerFindAllForUser = (
  id: string | undefined | null,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>(
    { url: `/events/${id}`, method: 'GET', signal },
    options
  );
};

export const getEventsControllerFindAllForUserQueryKey = (
  id: string | undefined | null
) => {
  return [`/events/${id}`] as const;
};

export const getEventsControllerFindAllForUserQueryOptions = <
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getEventsControllerFindAllForUserQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
  > = ({ signal }) =>
    eventsControllerFindAllForUser(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EventsControllerFindAllForUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
>;
export type EventsControllerFindAllForUserQueryError = ErrorType<unknown>;

export const useEventsControllerFindAllForUser = <
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getEventsControllerFindAllForUserQueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getEventsControllerFindAllForUserSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getEventsControllerFindAllForUserQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
  > = ({ signal }) =>
    eventsControllerFindAllForUser(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EventsControllerFindAllForUserSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
>;
export type EventsControllerFindAllForUserSuspenseQueryError =
  ErrorType<unknown>;

export const useEventsControllerFindAllForUserSuspense = <
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getEventsControllerFindAllForUserSuspenseQueryOptions(
    id,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const eventsControllerRemoveEvent = (
  id: string | undefined | null,
  removeEventDto: BodyType<RemoveEventDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/events/${id}`,
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      data: removeEventDto,
    },
    options
  );
};

export const getEventsControllerRemoveEventMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
    TError,
    { id: string; data: BodyType<RemoveEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
  TError,
  { id: string; data: BodyType<RemoveEventDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
    { id: string; data: BodyType<RemoveEventDto> }
  > = props => {
    const { id, data } = props ?? {};

    return eventsControllerRemoveEvent(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EventsControllerRemoveEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerRemoveEvent>>
>;
export type EventsControllerRemoveEventMutationBody = BodyType<RemoveEventDto>;
export type EventsControllerRemoveEventMutationError = ErrorType<unknown>;

export const useEventsControllerRemoveEvent = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
    TError,
    { id: string; data: BodyType<RemoveEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions =
    getEventsControllerRemoveEventMutationOptions(options);

  return useMutation(mutationOptions);
};
