/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  ApiErrorResponse,
  CreateEventDto,
  EventObject,
  Events,
  EventsControllerFindAllForUserParams,
  UpdateEventDto,
} from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const eventsControllerAddNew = (
  apartmentId: string | undefined | null,
  createEventDto: BodyType<CreateEventDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<Events>(
    {
      url: `/events/${apartmentId}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createEventDto,
    },
    options
  );
};

export const getEventsControllerAddNewMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerAddNew>>,
    TError,
    { apartmentId: string; data: BodyType<CreateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof eventsControllerAddNew>>,
  TError,
  { apartmentId: string; data: BodyType<CreateEventDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof eventsControllerAddNew>>,
    { apartmentId: string; data: BodyType<CreateEventDto> }
  > = props => {
    const { apartmentId, data } = props ?? {};

    return eventsControllerAddNew(apartmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EventsControllerAddNewMutationResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerAddNew>>
>;
export type EventsControllerAddNewMutationBody = BodyType<CreateEventDto>;
export type EventsControllerAddNewMutationError = ErrorType<unknown>;

export const useEventsControllerAddNew = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerAddNew>>,
    TError,
    { apartmentId: string; data: BodyType<CreateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof eventsControllerAddNew>>,
  TError,
  { apartmentId: string; data: BodyType<CreateEventDto> },
  TContext
> => {
  const mutationOptions = getEventsControllerAddNewMutationOptions(options);

  return useMutation(mutationOptions);
};
export const eventsControllerUpdateExisting = (
  apartmentId: string | undefined | null,
  updateEventDto: BodyType<UpdateEventDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/events/${apartmentId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateEventDto,
    },
    options
  );
};

export const getEventsControllerUpdateExistingMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
    TError,
    { apartmentId: string; data: BodyType<UpdateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
  TError,
  { apartmentId: string; data: BodyType<UpdateEventDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
    { apartmentId: string; data: BodyType<UpdateEventDto> }
  > = props => {
    const { apartmentId, data } = props ?? {};

    return eventsControllerUpdateExisting(apartmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EventsControllerUpdateExistingMutationResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerUpdateExisting>>
>;
export type EventsControllerUpdateExistingMutationBody =
  BodyType<UpdateEventDto>;
export type EventsControllerUpdateExistingMutationError = ErrorType<unknown>;

export const useEventsControllerUpdateExisting = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
    TError,
    { apartmentId: string; data: BodyType<UpdateEventDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof eventsControllerUpdateExisting>>,
  TError,
  { apartmentId: string; data: BodyType<UpdateEventDto> },
  TContext
> => {
  const mutationOptions =
    getEventsControllerUpdateExistingMutationOptions(options);

  return useMutation(mutationOptions);
};
export const eventsControllerFindAllForUser = (
  apartmentId: string | undefined | null,
  params?: EventsControllerFindAllForUserParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<Events>(
    { url: `/events/${apartmentId}`, method: 'GET', params, signal },
    options
  );
};

export const getEventsControllerFindAllForUserQueryKey = (
  apartmentId: string | undefined | null,
  params?: EventsControllerFindAllForUserParams
) => {
  return [`/events/${apartmentId}`, ...(params ? [params] : [])] as const;
};

export const getEventsControllerFindAllForUserQueryOptions = <
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string | undefined | null,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getEventsControllerFindAllForUserQueryKey(apartmentId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
  > = ({ signal }) =>
    eventsControllerFindAllForUser(apartmentId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!apartmentId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EventsControllerFindAllForUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
>;
export type EventsControllerFindAllForUserQueryError = ErrorType<unknown>;

export function useEventsControllerFindAllForUser<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string,
  params: undefined | EventsControllerFindAllForUserParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useEventsControllerFindAllForUser<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useEventsControllerFindAllForUser<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useEventsControllerFindAllForUser<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string | undefined | null,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getEventsControllerFindAllForUserQueryOptions(
    apartmentId,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getEventsControllerFindAllForUserSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string | undefined | null,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getEventsControllerFindAllForUserQueryKey(apartmentId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
  > = ({ signal }) =>
    eventsControllerFindAllForUser(apartmentId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!apartmentId,
    ...queryOptions,
  } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EventsControllerFindAllForUserSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerFindAllForUser>>
>;
export type EventsControllerFindAllForUserSuspenseQueryError =
  ErrorType<unknown>;

export function useEventsControllerFindAllForUserSuspense<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string,
  params: undefined | EventsControllerFindAllForUserParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useEventsControllerFindAllForUserSuspense<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useEventsControllerFindAllForUserSuspense<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useEventsControllerFindAllForUserSuspense<
  TData = Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
  TError = ErrorType<unknown>,
>(
  apartmentId: string | undefined | null,
  params?: EventsControllerFindAllForUserParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof eventsControllerFindAllForUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getEventsControllerFindAllForUserSuspenseQueryOptions(
    apartmentId,
    params,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const eventsControllerRemoveEvent = (
  apartmentId: string | undefined | null,
  eventObject: BodyType<EventObject>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/events/${apartmentId}`,
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      data: eventObject,
    },
    options
  );
};

export const getEventsControllerRemoveEventMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
    TError,
    { apartmentId: string; data: BodyType<EventObject> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
  TError,
  { apartmentId: string; data: BodyType<EventObject> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
    { apartmentId: string; data: BodyType<EventObject> }
  > = props => {
    const { apartmentId, data } = props ?? {};

    return eventsControllerRemoveEvent(apartmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EventsControllerRemoveEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof eventsControllerRemoveEvent>>
>;
export type EventsControllerRemoveEventMutationBody = BodyType<EventObject>;
export type EventsControllerRemoveEventMutationError =
  ErrorType<ApiErrorResponse>;

export const useEventsControllerRemoveEvent = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
    TError,
    { apartmentId: string; data: BodyType<EventObject> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof eventsControllerRemoveEvent>>,
  TError,
  { apartmentId: string; data: BodyType<EventObject> },
  TContext
> => {
  const mutationOptions =
    getEventsControllerRemoveEventMutationOptions(options);

  return useMutation(mutationOptions);
};
