/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  PublicEventsControllerFindAllForApartmentParams,
  PublicEventsResponse,
} from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const publicEventsControllerFindAllForApartment = (
  apartmentId: string | undefined | null,
  params?: PublicEventsControllerFindAllForApartmentParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<PublicEventsResponse>(
    { url: `/publicEvents/${apartmentId}`, method: 'GET', params, signal },
    options
  );
};

export const getPublicEventsControllerFindAllForApartmentQueryKey = (
  apartmentId: string | undefined | null,
  params?: PublicEventsControllerFindAllForApartmentParams
) => {
  return [`/publicEvents/${apartmentId}`, ...(params ? [params] : [])] as const;
};

export const getPublicEventsControllerFindAllForApartmentQueryOptions = <
  TData = Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
  TError = ErrorType<void>,
>(
  apartmentId: string | undefined | null,
  params?: PublicEventsControllerFindAllForApartmentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPublicEventsControllerFindAllForApartmentQueryKey(apartmentId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>
  > = ({ signal }) =>
    publicEventsControllerFindAllForApartment(
      apartmentId,
      params,
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    enabled: !!apartmentId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PublicEventsControllerFindAllForApartmentQueryResult = NonNullable<
  Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>
>;
export type PublicEventsControllerFindAllForApartmentQueryError =
  ErrorType<void>;

export const usePublicEventsControllerFindAllForApartment = <
  TData = Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
  TError = ErrorType<void>,
>(
  apartmentId: string | undefined | null,
  params?: PublicEventsControllerFindAllForApartmentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getPublicEventsControllerFindAllForApartmentQueryOptions(
    apartmentId,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getPublicEventsControllerFindAllForApartmentSuspenseQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof publicEventsControllerFindAllForApartment>
    >,
    TError = ErrorType<void>,
  >(
    apartmentId: string | undefined | null,
    params?: PublicEventsControllerFindAllForApartmentParams,
    options?: {
      query?: Partial<
        UseSuspenseQueryOptions<
          Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof customClient>;
    }
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getPublicEventsControllerFindAllForApartmentQueryKey(apartmentId, params);

    const queryFn: QueryFunction<
      Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>
    > = ({ signal }) =>
      publicEventsControllerFindAllForApartment(
        apartmentId,
        params,
        requestOptions,
        signal
      );

    return {
      queryKey,
      queryFn,
      enabled: !!apartmentId,
      ...queryOptions,
    } as UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
      TError,
      TData
    > & { queryKey: QueryKey };
  };

export type PublicEventsControllerFindAllForApartmentSuspenseQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>
  >;
export type PublicEventsControllerFindAllForApartmentSuspenseQueryError =
  ErrorType<void>;

export const usePublicEventsControllerFindAllForApartmentSuspense = <
  TData = Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
  TError = ErrorType<void>,
>(
  apartmentId: string | undefined | null,
  params?: PublicEventsControllerFindAllForApartmentParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof publicEventsControllerFindAllForApartment>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getPublicEventsControllerFindAllForApartmentSuspenseQueryOptions(
      apartmentId,
      params,
      options
    );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
