/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  ApiErrorResponse,
  CreateGuestDto,
  GuestObject,
  Guests,
  GuestsControllerCreateParams,
  GuestsControllerFindAllParams,
  GuestsControllerFindOneParams,
  GuestsControllerUpdateParams,
  RemoveGuestDto,
  UpdateGuestDto,
} from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const guestsControllerCreate = (
  createGuestDto: BodyType<CreateGuestDto>,
  params: GuestsControllerCreateParams,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<GuestObject>(
    {
      url: `/guests`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createGuestDto,
      params,
    },
    options
  );
};

export const getGuestsControllerCreateMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerCreate>>,
    TError,
    { data: BodyType<CreateGuestDto>; params: GuestsControllerCreateParams },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof guestsControllerCreate>>,
  TError,
  { data: BodyType<CreateGuestDto>; params: GuestsControllerCreateParams },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof guestsControllerCreate>>,
    { data: BodyType<CreateGuestDto>; params: GuestsControllerCreateParams }
  > = props => {
    const { data, params } = props ?? {};

    return guestsControllerCreate(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GuestsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerCreate>>
>;
export type GuestsControllerCreateMutationBody = BodyType<CreateGuestDto>;
export type GuestsControllerCreateMutationError = ErrorType<ApiErrorResponse>;

export const useGuestsControllerCreate = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerCreate>>,
    TError,
    { data: BodyType<CreateGuestDto>; params: GuestsControllerCreateParams },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof guestsControllerCreate>>,
  TError,
  { data: BodyType<CreateGuestDto>; params: GuestsControllerCreateParams },
  TContext
> => {
  const mutationOptions = getGuestsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const guestsControllerFindAll = (
  params: GuestsControllerFindAllParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<Guests>(
    { url: `/guests`, method: 'GET', params, signal },
    options
  );
};

export const getGuestsControllerFindAllQueryKey = (
  params: GuestsControllerFindAllParams
) => {
  return [`/guests`, ...(params ? [params] : [])] as const;
};

export const getGuestsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGuestsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindAll>>
  > = ({ signal }) => guestsControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindAll>>
>;
export type GuestsControllerFindAllQueryError = ErrorType<unknown>;

export function useGuestsControllerFindAll<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof guestsControllerFindAll>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindAll<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof guestsControllerFindAll>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindAll<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useGuestsControllerFindAll<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGuestsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGuestsControllerFindAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGuestsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindAll>>
  > = ({ signal }) => guestsControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindAllSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindAll>>
>;
export type GuestsControllerFindAllSuspenseQueryError = ErrorType<unknown>;

export function useGuestsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useGuestsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGuestsControllerFindAllSuspenseQueryOptions(
    params,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const guestsControllerUpdate = (
  updateGuestDto: BodyType<UpdateGuestDto>,
  params: GuestsControllerUpdateParams,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<Guests>(
    {
      url: `/guests`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateGuestDto,
      params,
    },
    options
  );
};

export const getGuestsControllerUpdateMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerUpdate>>,
    TError,
    { data: BodyType<UpdateGuestDto>; params: GuestsControllerUpdateParams },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof guestsControllerUpdate>>,
  TError,
  { data: BodyType<UpdateGuestDto>; params: GuestsControllerUpdateParams },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof guestsControllerUpdate>>,
    { data: BodyType<UpdateGuestDto>; params: GuestsControllerUpdateParams }
  > = props => {
    const { data, params } = props ?? {};

    return guestsControllerUpdate(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GuestsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerUpdate>>
>;
export type GuestsControllerUpdateMutationBody = BodyType<UpdateGuestDto>;
export type GuestsControllerUpdateMutationError = ErrorType<ApiErrorResponse>;

export const useGuestsControllerUpdate = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerUpdate>>,
    TError,
    { data: BodyType<UpdateGuestDto>; params: GuestsControllerUpdateParams },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof guestsControllerUpdate>>,
  TError,
  { data: BodyType<UpdateGuestDto>; params: GuestsControllerUpdateParams },
  TContext
> => {
  const mutationOptions = getGuestsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const guestsControllerFindOne = (
  params: GuestsControllerFindOneParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<Guests>(
    { url: `/guests/guest`, method: 'GET', params, signal },
    options
  );
};

export const getGuestsControllerFindOneQueryKey = (
  params: GuestsControllerFindOneParams
) => {
  return [`/guests/guest`, ...(params ? [params] : [])] as const;
};

export const getGuestsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGuestsControllerFindOneQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindOne>>
  > = ({ signal }) => guestsControllerFindOne(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindOne>>
>;
export type GuestsControllerFindOneQueryError = ErrorType<unknown>;

export function useGuestsControllerFindOne<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof guestsControllerFindOne>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindOne<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof guestsControllerFindOne>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindOne<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useGuestsControllerFindOne<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGuestsControllerFindOneQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGuestsControllerFindOneSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGuestsControllerFindOneQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindOne>>
  > = ({ signal }) => guestsControllerFindOne(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindOneSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindOne>>
>;
export type GuestsControllerFindOneSuspenseQueryError = ErrorType<unknown>;

export function useGuestsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGuestsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useGuestsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  params: GuestsControllerFindOneParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGuestsControllerFindOneSuspenseQueryOptions(
    params,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const guestsControllerRemove = (
  apartmentId: string | undefined | null,
  removeGuestDto: BodyType<RemoveGuestDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<Guests>(
    {
      url: `/guests/${apartmentId}`,
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      data: removeGuestDto,
    },
    options
  );
};

export const getGuestsControllerRemoveMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerRemove>>,
    TError,
    { apartmentId: string; data: BodyType<RemoveGuestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof guestsControllerRemove>>,
  TError,
  { apartmentId: string; data: BodyType<RemoveGuestDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof guestsControllerRemove>>,
    { apartmentId: string; data: BodyType<RemoveGuestDto> }
  > = props => {
    const { apartmentId, data } = props ?? {};

    return guestsControllerRemove(apartmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GuestsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerRemove>>
>;
export type GuestsControllerRemoveMutationBody = BodyType<RemoveGuestDto>;
export type GuestsControllerRemoveMutationError = ErrorType<ApiErrorResponse>;

export const useGuestsControllerRemove = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerRemove>>,
    TError,
    { apartmentId: string; data: BodyType<RemoveGuestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof guestsControllerRemove>>,
  TError,
  { apartmentId: string; data: BodyType<RemoveGuestDto> },
  TContext
> => {
  const mutationOptions = getGuestsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
