/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type { CreateGuestDto, RemoveGuestDto } from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const guestsControllerCreateOrUpdate = (
  apartmentId: string | undefined | null,
  createGuestDto: BodyType<CreateGuestDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/guests/${apartmentId}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createGuestDto,
    },
    options
  );
};

export const getGuestsControllerCreateOrUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerCreateOrUpdate>>,
    TError,
    { apartmentId: string; data: BodyType<CreateGuestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof guestsControllerCreateOrUpdate>>,
  TError,
  { apartmentId: string; data: BodyType<CreateGuestDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof guestsControllerCreateOrUpdate>>,
    { apartmentId: string; data: BodyType<CreateGuestDto> }
  > = props => {
    const { apartmentId, data } = props ?? {};

    return guestsControllerCreateOrUpdate(apartmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GuestsControllerCreateOrUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerCreateOrUpdate>>
>;
export type GuestsControllerCreateOrUpdateMutationBody =
  BodyType<CreateGuestDto>;
export type GuestsControllerCreateOrUpdateMutationError = ErrorType<unknown>;

export const useGuestsControllerCreateOrUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerCreateOrUpdate>>,
    TError,
    { apartmentId: string; data: BodyType<CreateGuestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions =
    getGuestsControllerCreateOrUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const guestsControllerRemove = (
  apartmentId: string | undefined | null,
  removeGuestDto: BodyType<RemoveGuestDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/guests/${apartmentId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: removeGuestDto,
    },
    options
  );
};

export const getGuestsControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerRemove>>,
    TError,
    { apartmentId: string; data: BodyType<RemoveGuestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof guestsControllerRemove>>,
  TError,
  { apartmentId: string; data: BodyType<RemoveGuestDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof guestsControllerRemove>>,
    { apartmentId: string; data: BodyType<RemoveGuestDto> }
  > = props => {
    const { apartmentId, data } = props ?? {};

    return guestsControllerRemove(apartmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GuestsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerRemove>>
>;
export type GuestsControllerRemoveMutationBody = BodyType<RemoveGuestDto>;
export type GuestsControllerRemoveMutationError = ErrorType<unknown>;

export const useGuestsControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof guestsControllerRemove>>,
    TError,
    { apartmentId: string; data: BodyType<RemoveGuestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getGuestsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
export const guestsControllerFindAll = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>({ url: `/guests`, method: 'GET', signal }, options);
};

export const getGuestsControllerFindAllQueryKey = () => {
  return [`/guests`] as const;
};

export const getGuestsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof guestsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGuestsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindAll>>
  > = ({ signal }) => guestsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindAll>>
>;
export type GuestsControllerFindAllQueryError = ErrorType<unknown>;

export const useGuestsControllerFindAll = <
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof guestsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGuestsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGuestsControllerFindAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof guestsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGuestsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindAll>>
  > = ({ signal }) => guestsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindAllSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindAll>>
>;
export type GuestsControllerFindAllSuspenseQueryError = ErrorType<unknown>;

export const useGuestsControllerFindAllSuspense = <
  TData = Awaited<ReturnType<typeof guestsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof guestsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGuestsControllerFindAllSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const guestsControllerFindOne = (
  id: string | undefined | null,
  selectedyear: string | undefined | null,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>(
    { url: `/guests/${id}/${selectedyear}`, method: 'GET', signal },
    options
  );
};

export const getGuestsControllerFindOneQueryKey = (
  id: string | undefined | null,
  selectedyear: string | undefined | null
) => {
  return [`/guests/${id}/${selectedyear}`] as const;
};

export const getGuestsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  selectedyear: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGuestsControllerFindOneQueryKey(id, selectedyear);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindOne>>
  > = ({ signal }) =>
    guestsControllerFindOne(id, selectedyear, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && selectedyear),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindOne>>
>;
export type GuestsControllerFindOneQueryError = ErrorType<unknown>;

export const useGuestsControllerFindOne = <
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  selectedyear: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGuestsControllerFindOneQueryOptions(
    id,
    selectedyear,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGuestsControllerFindOneSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  selectedyear: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGuestsControllerFindOneQueryKey(id, selectedyear);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof guestsControllerFindOne>>
  > = ({ signal }) =>
    guestsControllerFindOne(id, selectedyear, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(id && selectedyear),
    ...queryOptions,
  } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof guestsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GuestsControllerFindOneSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof guestsControllerFindOne>>
>;
export type GuestsControllerFindOneSuspenseQueryError = ErrorType<unknown>;

export const useGuestsControllerFindOneSuspense = <
  TData = Awaited<ReturnType<typeof guestsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  selectedyear: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof guestsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGuestsControllerFindOneSuspenseQueryOptions(
    id,
    selectedyear,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
