/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  ApiErrorResponse,
  CreateUserDto,
  LoginResponse,
} from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const authenticationControllerRegister = (
  createUserDto: BodyType<CreateUserDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/authentication/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserDto,
    },
    options
  );
};

export const getAuthenticationControllerRegisterMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authenticationControllerRegister>>,
    TError,
    { data: BodyType<CreateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authenticationControllerRegister>>,
  TError,
  { data: BodyType<CreateUserDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authenticationControllerRegister>>,
    { data: BodyType<CreateUserDto> }
  > = props => {
    const { data } = props ?? {};

    return authenticationControllerRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthenticationControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof authenticationControllerRegister>>
>;
export type AuthenticationControllerRegisterMutationBody =
  BodyType<CreateUserDto>;
export type AuthenticationControllerRegisterMutationError = ErrorType<unknown>;

export const useAuthenticationControllerRegister = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authenticationControllerRegister>>,
    TError,
    { data: BodyType<CreateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions =
    getAuthenticationControllerRegisterMutationOptions(options);

  return useMutation(mutationOptions);
};
export const authenticationControllerLogIn = (
  createUserDto: BodyType<CreateUserDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<LoginResponse>(
    {
      url: `/authentication/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserDto,
    },
    options
  );
};

export const getAuthenticationControllerLogInMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authenticationControllerLogIn>>,
    TError,
    { data: BodyType<CreateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authenticationControllerLogIn>>,
  TError,
  { data: BodyType<CreateUserDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authenticationControllerLogIn>>,
    { data: BodyType<CreateUserDto> }
  > = props => {
    const { data } = props ?? {};

    return authenticationControllerLogIn(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthenticationControllerLogInMutationResult = NonNullable<
  Awaited<ReturnType<typeof authenticationControllerLogIn>>
>;
export type AuthenticationControllerLogInMutationBody = BodyType<CreateUserDto>;
export type AuthenticationControllerLogInMutationError =
  ErrorType<ApiErrorResponse>;

export const useAuthenticationControllerLogIn = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authenticationControllerLogIn>>,
    TError,
    { data: BodyType<CreateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions =
    getAuthenticationControllerLogInMutationOptions(options);

  return useMutation(mutationOptions);
};
export const authenticationControllerGoogleAuth = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>(
    { url: `/authentication/google/login`, method: 'GET', signal },
    options
  );
};

export const getAuthenticationControllerGoogleAuthQueryKey = () => {
  return [`/authentication/google/login`] as const;
};

export const getAuthenticationControllerGoogleAuthQueryOptions = <
  TData = Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthenticationControllerGoogleAuthQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>
  > = ({ signal }) =>
    authenticationControllerGoogleAuth(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthenticationControllerGoogleAuthQueryResult = NonNullable<
  Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>
>;
export type AuthenticationControllerGoogleAuthQueryError = ErrorType<unknown>;

export const useAuthenticationControllerGoogleAuth = <
  TData = Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getAuthenticationControllerGoogleAuthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAuthenticationControllerGoogleAuthSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthenticationControllerGoogleAuthQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>
  > = ({ signal }) =>
    authenticationControllerGoogleAuth(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthenticationControllerGoogleAuthSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>
>;
export type AuthenticationControllerGoogleAuthSuspenseQueryError =
  ErrorType<unknown>;

export const useAuthenticationControllerGoogleAuthSuspense = <
  TData = Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuth>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getAuthenticationControllerGoogleAuthSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const authenticationControllerGoogleAuthRedirect = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>(
    { url: `/authentication/google/redirect`, method: 'GET', signal },
    options
  );
};

export const getAuthenticationControllerGoogleAuthRedirectQueryKey = () => {
  return [`/authentication/google/redirect`] as const;
};

export const getAuthenticationControllerGoogleAuthRedirectQueryOptions = <
  TData = Awaited<
    ReturnType<typeof authenticationControllerGoogleAuthRedirect>
  >,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAuthenticationControllerGoogleAuthRedirectQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>
  > = ({ signal }) =>
    authenticationControllerGoogleAuthRedirect(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthenticationControllerGoogleAuthRedirectQueryResult = NonNullable<
  Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>
>;
export type AuthenticationControllerGoogleAuthRedirectQueryError =
  ErrorType<unknown>;

export const useAuthenticationControllerGoogleAuthRedirect = <
  TData = Awaited<
    ReturnType<typeof authenticationControllerGoogleAuthRedirect>
  >,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getAuthenticationControllerGoogleAuthRedirectQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAuthenticationControllerGoogleAuthRedirectSuspenseQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof authenticationControllerGoogleAuthRedirect>
    >,
    TError = ErrorType<unknown>
  >(options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getAuthenticationControllerGoogleAuthRedirectQueryKey();

    const queryFn: QueryFunction<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>
    > = ({ signal }) =>
      authenticationControllerGoogleAuthRedirect(requestOptions, signal);

    return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>,
      TError,
      TData
    > & { queryKey: QueryKey };
  };

export type AuthenticationControllerGoogleAuthRedirectSuspenseQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>
  >;
export type AuthenticationControllerGoogleAuthRedirectSuspenseQueryError =
  ErrorType<unknown>;

export const useAuthenticationControllerGoogleAuthRedirectSuspense = <
  TData = Awaited<
    ReturnType<typeof authenticationControllerGoogleAuthRedirect>
  >,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerGoogleAuthRedirect>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getAuthenticationControllerGoogleAuthRedirectSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const authenticationControllerRefresh = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>(
    { url: `/authentication/refresh`, method: 'GET', signal },
    options
  );
};

export const getAuthenticationControllerRefreshQueryKey = () => {
  return [`/authentication/refresh`] as const;
};

export const getAuthenticationControllerRefreshQueryOptions = <
  TData = Awaited<ReturnType<typeof authenticationControllerRefresh>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerRefresh>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthenticationControllerRefreshQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authenticationControllerRefresh>>
  > = ({ signal }) => authenticationControllerRefresh(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authenticationControllerRefresh>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthenticationControllerRefreshQueryResult = NonNullable<
  Awaited<ReturnType<typeof authenticationControllerRefresh>>
>;
export type AuthenticationControllerRefreshQueryError = ErrorType<unknown>;

export const useAuthenticationControllerRefresh = <
  TData = Awaited<ReturnType<typeof authenticationControllerRefresh>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerRefresh>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAuthenticationControllerRefreshQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAuthenticationControllerRefreshSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof authenticationControllerRefresh>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerRefresh>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthenticationControllerRefreshQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authenticationControllerRefresh>>
  > = ({ signal }) => authenticationControllerRefresh(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof authenticationControllerRefresh>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthenticationControllerRefreshSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof authenticationControllerRefresh>>
>;
export type AuthenticationControllerRefreshSuspenseQueryError =
  ErrorType<unknown>;

export const useAuthenticationControllerRefreshSuspense = <
  TData = Awaited<ReturnType<typeof authenticationControllerRefresh>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof authenticationControllerRefresh>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getAuthenticationControllerRefreshSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
