/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  ApiErrorResponse,
  CreateApartmentDto,
  SingleApartmentDto,
  UpdateApartmentDto,
} from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const apartmentsControllerCreate = (
  createApartmentDto: BodyType<CreateApartmentDto>,
  options?: SecondParameter<typeof customClient>
) => {
  const formData = new FormData();
  formData.append('name', createApartmentDto.name);
  if (createApartmentDto.image !== undefined) {
    formData.append('image', createApartmentDto.image);
  }
  formData.append('address', createApartmentDto.address);
  if (createApartmentDto.owner !== undefined) {
    formData.append('owner', createApartmentDto.owner);
  }
  if (createApartmentDto.pid !== undefined) {
    formData.append('pid', createApartmentDto.pid);
  }
  if (createApartmentDto.iban !== undefined) {
    formData.append('iban', createApartmentDto.iban);
  }
  formData.append('email', createApartmentDto.email);
  if (createApartmentDto.pricePerNight !== undefined) {
    formData.append(
      'pricePerNight',
      createApartmentDto.pricePerNight.toString()
    );
  }

  return customClient<SingleApartmentDto>(
    {
      url: `/apartments`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options
  );
};

export const getApartmentsControllerCreateMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerCreate>>,
    TError,
    { data: BodyType<CreateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apartmentsControllerCreate>>,
  TError,
  { data: BodyType<CreateApartmentDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apartmentsControllerCreate>>,
    { data: BodyType<CreateApartmentDto> }
  > = props => {
    const { data } = props ?? {};

    return apartmentsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApartmentsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerCreate>>
>;
export type ApartmentsControllerCreateMutationBody =
  BodyType<CreateApartmentDto>;
export type ApartmentsControllerCreateMutationError =
  ErrorType<ApiErrorResponse>;

export const useApartmentsControllerCreate = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerCreate>>,
    TError,
    { data: BodyType<CreateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apartmentsControllerCreate>>,
  TError,
  { data: BodyType<CreateApartmentDto> },
  TContext
> => {
  const mutationOptions = getApartmentsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apartmentsControllerFindAll = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<SingleApartmentDto[]>(
    { url: `/apartments`, method: 'GET', signal },
    options
  );
};

export const getApartmentsControllerFindAllQueryKey = () => {
  return [`/apartments`] as const;
};

export const getApartmentsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>
  > = ({ signal }) => apartmentsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindAll>>
>;
export type ApartmentsControllerFindAllQueryError = ErrorType<ApiErrorResponse>;

export function useApartmentsControllerFindAll<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customClient>;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindAll<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindAll<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useApartmentsControllerFindAll<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApartmentsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApartmentsControllerFindAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>
  > = ({ signal }) => apartmentsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindAllSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindAll>>
>;
export type ApartmentsControllerFindAllSuspenseQueryError =
  ErrorType<ApiErrorResponse>;

export function useApartmentsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options: {
  query: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useApartmentsControllerFindAllSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<ApiErrorResponse>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getApartmentsControllerFindAllSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apartmentsControllerFindOne = (
  id: string | undefined | null,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<SingleApartmentDto>(
    { url: `/apartments/${id}`, method: 'GET', signal },
    options
  );
};

export const getApartmentsControllerFindOneQueryKey = (
  id: string | undefined | null
) => {
  return [`/apartments/${id}`] as const;
};

export const getApartmentsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>
  > = ({ signal }) => apartmentsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindOne>>
>;
export type ApartmentsControllerFindOneQueryError = ErrorType<ApiErrorResponse>;

export function useApartmentsControllerFindOne<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindOne<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindOne<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useApartmentsControllerFindOne<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApartmentsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApartmentsControllerFindOneSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>
  > = ({ signal }) => apartmentsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindOneSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindOne>>
>;
export type ApartmentsControllerFindOneSuspenseQueryError =
  ErrorType<ApiErrorResponse>;

export function useApartmentsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useApartmentsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useApartmentsControllerFindOneSuspense<
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<ApiErrorResponse>,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getApartmentsControllerFindOneSuspenseQueryOptions(
    id,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const apartmentsControllerUpdate = (
  apartmentId: string | undefined | null,
  updateApartmentDto: BodyType<UpdateApartmentDto>,
  options?: SecondParameter<typeof customClient>
) => {
  const formData = new FormData();
  formData.append('name', updateApartmentDto.name);
  if (updateApartmentDto.image !== undefined) {
    formData.append('image', updateApartmentDto.image);
  }
  formData.append('address', updateApartmentDto.address);
  if (updateApartmentDto.owner !== undefined) {
    formData.append('owner', updateApartmentDto.owner);
  }
  if (updateApartmentDto.pid !== undefined) {
    formData.append('pid', updateApartmentDto.pid);
  }
  if (updateApartmentDto.iban !== undefined) {
    formData.append('iban', updateApartmentDto.iban);
  }
  formData.append('email', updateApartmentDto.email);
  if (updateApartmentDto.pricePerNight !== undefined) {
    formData.append(
      'pricePerNight',
      updateApartmentDto.pricePerNight.toString()
    );
  }

  return customClient<SingleApartmentDto>(
    {
      url: `/apartments/${apartmentId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options
  );
};

export const getApartmentsControllerUpdateMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
    TError,
    { apartmentId: string; data: BodyType<UpdateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
  TError,
  { apartmentId: string; data: BodyType<UpdateApartmentDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
    { apartmentId: string; data: BodyType<UpdateApartmentDto> }
  > = props => {
    const { apartmentId, data } = props ?? {};

    return apartmentsControllerUpdate(apartmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApartmentsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerUpdate>>
>;
export type ApartmentsControllerUpdateMutationBody =
  BodyType<UpdateApartmentDto>;
export type ApartmentsControllerUpdateMutationError =
  ErrorType<ApiErrorResponse>;

export const useApartmentsControllerUpdate = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
    TError,
    { apartmentId: string; data: BodyType<UpdateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
  TError,
  { apartmentId: string; data: BodyType<UpdateApartmentDto> },
  TContext
> => {
  const mutationOptions = getApartmentsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apartmentsControllerRemove = (
  apartmentId: string | undefined | null,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<SingleApartmentDto>(
    { url: `/apartments/${apartmentId}`, method: 'DELETE' },
    options
  );
};

export const getApartmentsControllerRemoveMutationOptions = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerRemove>>,
    TError,
    { apartmentId: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apartmentsControllerRemove>>,
  TError,
  { apartmentId: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apartmentsControllerRemove>>,
    { apartmentId: string }
  > = props => {
    const { apartmentId } = props ?? {};

    return apartmentsControllerRemove(apartmentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApartmentsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerRemove>>
>;

export type ApartmentsControllerRemoveMutationError =
  ErrorType<ApiErrorResponse>;

export const useApartmentsControllerRemove = <
  TError = ErrorType<ApiErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerRemove>>,
    TError,
    { apartmentId: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof apartmentsControllerRemove>>,
  TError,
  { apartmentId: string },
  TContext
> => {
  const mutationOptions = getApartmentsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
