/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Booking calendar API
 * Booking calendar API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  CreateApartmentDto,
  UpdateApartmentDto,
} from '../../openapi-schemas';
import { customClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const apartmentsControllerCreate = (
  createApartmentDto: BodyType<CreateApartmentDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/apartments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createApartmentDto,
    },
    options
  );
};

export const getApartmentsControllerCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerCreate>>,
    TError,
    { data: BodyType<CreateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apartmentsControllerCreate>>,
  TError,
  { data: BodyType<CreateApartmentDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apartmentsControllerCreate>>,
    { data: BodyType<CreateApartmentDto> }
  > = props => {
    const { data } = props ?? {};

    return apartmentsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApartmentsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerCreate>>
>;
export type ApartmentsControllerCreateMutationBody =
  BodyType<CreateApartmentDto>;
export type ApartmentsControllerCreateMutationError = ErrorType<unknown>;

export const useApartmentsControllerCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerCreate>>,
    TError,
    { data: BodyType<CreateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getApartmentsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apartmentsControllerFindAll = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>(
    { url: `/apartments`, method: 'GET', signal },
    options
  );
};

export const getApartmentsControllerFindAllQueryKey = () => {
  return [`/apartments`] as const;
};

export const getApartmentsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>
  > = ({ signal }) => apartmentsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindAll>>
>;
export type ApartmentsControllerFindAllQueryError = ErrorType<unknown>;

export const useApartmentsControllerFindAll = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getApartmentsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getApartmentsControllerFindAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>
  > = ({ signal }) => apartmentsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindAllSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindAll>>
>;
export type ApartmentsControllerFindAllSuspenseQueryError = ErrorType<unknown>;

export const useApartmentsControllerFindAllSuspense = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof apartmentsControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customClient>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getApartmentsControllerFindAllSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const apartmentsControllerFindOne = (
  id: string | undefined | null,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<void>(
    { url: `/apartments/${id}`, method: 'GET', signal },
    options
  );
};

export const getApartmentsControllerFindOneQueryKey = (
  id: string | undefined | null
) => {
  return [`/apartments/${id}`] as const;
};

export const getApartmentsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>
  > = ({ signal }) => apartmentsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindOne>>
>;
export type ApartmentsControllerFindOneQueryError = ErrorType<unknown>;

export const useApartmentsControllerFindOne = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getApartmentsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getApartmentsControllerFindOneSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApartmentsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>
  > = ({ signal }) => apartmentsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ApartmentsControllerFindOneSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerFindOne>>
>;
export type ApartmentsControllerFindOneSuspenseQueryError = ErrorType<unknown>;

export const useApartmentsControllerFindOneSuspense = <
  TData = Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
  TError = ErrorType<unknown>
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof apartmentsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getApartmentsControllerFindOneSuspenseQueryOptions(
    id,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const apartmentsControllerUpdate = (
  id: string | undefined | null,
  updateApartmentDto: BodyType<UpdateApartmentDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    {
      url: `/apartments/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateApartmentDto,
    },
    options
  );
};

export const getApartmentsControllerUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateApartmentDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
    { id: string; data: BodyType<UpdateApartmentDto> }
  > = props => {
    const { id, data } = props ?? {};

    return apartmentsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApartmentsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerUpdate>>
>;
export type ApartmentsControllerUpdateMutationBody =
  BodyType<UpdateApartmentDto>;
export type ApartmentsControllerUpdateMutationError = ErrorType<unknown>;

export const useApartmentsControllerUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateApartmentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getApartmentsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const apartmentsControllerRemove = (
  id: string | undefined | null,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    { url: `/apartments/${id}`, method: 'DELETE' },
    options
  );
};

export const getApartmentsControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apartmentsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apartmentsControllerRemove>>,
    { id: string }
  > = props => {
    const { id } = props ?? {};

    return apartmentsControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApartmentsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof apartmentsControllerRemove>>
>;

export type ApartmentsControllerRemoveMutationError = ErrorType<unknown>;

export const useApartmentsControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apartmentsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getApartmentsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
